server {
    listen 80;
    server_name _;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    # Sirve los archivos estáticos (tu index.html)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Intercepta las peticiones a /api/ y las manda al Backend
    location /api/ {
        # REEMPLAZA ESTO CON LA IP PRIVADA REAL DE TU INSTANCIA EC2 DEL BACKEND
        proxy_pass http://10.0.10.192:3001; 

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
